sudo: required
services:
  - docker

before_install:
  - docker build -t pritamgawade/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pritamgawade/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker"
  env: "Docker-env"
  bucker_name: "elasticbeanstalk-ca-central-1-304512036982"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"